# Project information
site_name: MorphAL &mdash; Documentation
site_url: https://doc.ptm.huma-num.fr/morphal/
site_author: EG/EM (PTM)
site_description: >-
  MorphAL est un outil d'analyse morphologique, développé dans le cadre du Consortium Huma-Num
  Projets Time Machine (PTM).
#  <a href="https://ptm.huma-num.fr/" target="_blank">Projets Time Machine (PTM)</a>.

# Repository
repo_name: paristimemachine/morphal-documentation
repo_url: https://github.com/paristimemachine/morphal-documentation

# Copyright
copyright: <a href="https://ptm.huma-num.fr/" target="_blank">PTM</a> &mdash; 2021-2025

theme:
  name: material
  custom_dir: ./docs/overrides
  language: fr
#  logo: assets/images/logo.png
#  favicon: assets/images/logo-favicon.png

  features:
    # - header.autohide
    # - content.tabs.link
    # - navigation.expand
    - navigation.indexes
    - navigation.footer
    # - navigation.instant
    - navigation.sections
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    # - toc.integrate

  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/lightbulb # material/brightness-7 material/toggle-switch-off-outline / material/weather-sunny
        name: Passer en mode nuit # Passer en mode nuit / Switch to dark mode
        
    - media: "(prefers-color-scheme: dark)" 
      scheme: slate
      toggle:
        icon: material/lightbulb-outline # material/brightness-4 material/toggle-switch / material/weather-night
        name: Passer en mode jour # name: Passer en mode jour / Switch to light mode

# extra:
#   alternate:
#     - name: Français
#       link: /
#       lang: fr
#     - name: English
#       link: /en/
#       lang: en
#   version:
#     provider: mike

plugins:
  - search:
      separator: '[\s\-,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
      lang:
        - fr
        # - en
  - with-pdf: # Ubuntu 20+ as it requires libpango >= 1.44
      author: Eric Grosso et Eric Mermet (PTM)
      # copyright: ANY TEXT
      
      cover: true
      # back_cover: true
      # cover_logo: assets/images/logo.png
      cover_title: Documentation
      cover_subtitle: Français
      # custom_template_path: TEMPLATES PATH
      
      toc_title: MorphAL
      # heading_shift: false
      # toc_level: 3
      # ordered_chapter_level: 2
      # excludes_children:
      #    - 'release-notes/:upgrading'
      #    - 'release-notes/:changelog'
      
      # exclude_pages:
      #    - 'bugs/'
      #    - 'appendix/contribute/'
      # convert_iframe:
      #    - src: IFRAME SRC
      #      img: POSTER IMAGE URL
      #      text: ALTERNATE TEXT
      #    - src: ...
      # two_columns_level: 3
      
      # render_js: true
      # headless_chrome_path: headless-chromium

      output_path: /tmp/MorphAL-documentation.pdf
      enabled_if_env: ENABLE_PDF_EXPORT

      # debug_html: true
      # show_anchors: true
      # verbose: true

  - minify:
      minify_html: true
      minify_js: true
      minify_css: true
      htmlmin_opts:
        remove_comments: true
      cache_safe: true

# Customization
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/paristimemachine
    - icon: fontawesome/brands/bluesky
      link: https://bsky.app/profile/ptm-huma-num.bsky.social
    - icon: fontawesome/brands/x-twitter
      link: https://twitter.com/TimeParis

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - https://cdn.jsdelivr.net/npm/mathjax@3.2.2/es5/tex-mml-chtml.min.js
  # - js/MathJax.js
  # - https://polyfill.io/v3/polyfill.min.js?features=es6
  # - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.details
  - pymdownx.superfences
  - footnotes

# Page tree
nav:
  - Accueil: index.md
  - Présentation: presentation.md
  - Installation: installation.md
  - Traitements: traitements.md 
